# Generated by Django 5.2.17 on 2026-08-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_placeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='place_image',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
    ]
