# Generated by Django 5.2.17 on 2026-08-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_placeimage_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimage',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция'),
        ),
    ]
