# Generated by Django 5.2.17 on 2026-08-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_placeimage_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='place',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
