# Generated by Django 5.2.17 on 2026-08-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
        migrations.RemoveField(
            model_name='place',
            name='position',
        ),
    ]
