# Generated by Django 5.2.17 on 2026-08-17 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_options_remove_place_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeimage',
            old_name='place_image',
            new_name='image',
        ),
    ]
