# Generated by Django 5.2.17 on 2026-08-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_rename_place_image_placeimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
